// Do not edit: This code was generated by flatdata's generator.
#[allow(missing_docs)]
pub mod osm_ext {
#[allow(unused_imports)]
use flatdata::{flatdata_read_bytes, flatdata_write_bytes};


    /// Special value which represents an invalid index (matches `osm.INVALID_IDX`).
pub const INVALID_IDX: u64 = 1_099_511_627_775;
/// Fingerprint of the exact parent `Osm` archive this sidecar was built from.
///
/// A sidecar hard-codes parent entity indices and parent stringtable indices,
/// both of which change whenever the parent is recompiled or reordered. The
/// query layer compares this against the live parent and refuses to serve any
/// query on mismatch.
#[repr(transparent)]
#[derive(Clone)]
pub struct ExtHeader {
    data: [u8; 49],
}

impl ExtHeader {
    /// Unsafe since the struct might not be self-contained
    pub unsafe fn new_unchecked( ) -> Self {
        Self{data : [0; 49]}
    }
}

impl flatdata::Struct for ExtHeader {
    unsafe fn create_unchecked( ) -> Self {
        Self{data : [0; 49]}
    }

    const SIZE_IN_BYTES: usize = 49;
    const IS_OVERLAPPING_WITH_NEXT : bool = false;
}

impl ExtHeader {
    pub fn new( ) -> Self {
        Self{data : [0; 49]}
    }

    /// Create reference from byte array of matching size
    pub fn from_bytes(data: &[u8; 49]) -> &Self {
        // Safety: This is safe since ExtHeader is repr(transparent)
        unsafe{ std::mem::transmute( data ) }
    }

    /// Create reference from byte array of matching size
    pub fn from_bytes_mut(data: &mut [u8; 49]) -> &mut Self {
        // Safety: This is safe since ExtHeader is repr(transparent)
        unsafe{ std::mem::transmute( data ) }
    }

    /// Create reference from byte array
    pub fn from_bytes_slice(data: &[u8]) -> Result<&Self, flatdata::ResourceStorageError> {
        // We cannot rely on TryFrom here, since it does not yet support > 33 bytes
        if data.len() < 49 {
            assert_eq!(data.len(), 49);
            return Err(flatdata::ResourceStorageError::UnexpectedDataSize);
        }
        let ptr = data.as_ptr() as *const [u8; 49];
        // Safety: We checked length before
        Ok(Self::from_bytes(unsafe { &*ptr }))
    }

    /// Create reference from byte array
    pub fn from_bytes_slice_mut(data: &mut [u8]) -> Result<&mut Self, flatdata::ResourceStorageError> {
        // We cannot rely on TryFrom here, since it does not yet support > 33 bytes
        if data.len() < 49 {
            assert_eq!(data.len(), 49);
            return Err(flatdata::ResourceStorageError::UnexpectedDataSize);
        }
        let ptr = data.as_ptr() as *mut [u8; 49];
        // Safety: We checked length before
        Ok(Self::from_bytes_mut(unsafe { &mut *ptr }))
    }

    pub fn as_bytes(&self) -> &[u8; 49] {
        &self.data
    }
}

impl Default for ExtHeader {
    fn default( ) -> Self {
        Self::new( )
    }
}

unsafe impl flatdata::NoOverlap for ExtHeader {}

impl ExtHeader {
    /// Hash of the parent's embedded schema bytes (`osm.flatdata`).
    #[inline]
    pub fn parent_schema_hash(&self) -> u64 {
        let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 0, 64);
        unsafe { std::mem::transmute::<u64, u64>(value) }
    }

    /// Parent vector lengths at build time (cheap; catches rebuilds/reorders).
    #[inline]
    pub fn parent_node_count(&self) -> u64 {
        let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 64, 40);
        unsafe { std::mem::transmute::<u64, u64>(value) }
    }

    #[inline]
    pub fn parent_way_count(&self) -> u64 {
        let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 104, 40);
        unsafe { std::mem::transmute::<u64, u64>(value) }
    }

    #[inline]
    pub fn parent_relation_count(&self) -> u64 {
        let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 144, 40);
        unsafe { std::mem::transmute::<u64, u64>(value) }
    }

    #[inline]
    pub fn parent_tags_count(&self) -> u64 {
        let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 184, 40);
        unsafe { std::mem::transmute::<u64, u64>(value) }
    }

    #[inline]
    pub fn parent_stringtable_len(&self) -> u64 {
        let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 224, 64);
        unsafe { std::mem::transmute::<u64, u64>(value) }
    }

    /// Parent replication sequence number, or 0 if absent.
    #[inline]
    pub fn parent_replication_sequence_number(&self) -> i64 {
        let value = flatdata_read_bytes!(i64, self.data.as_ptr(), 288, 64);
        unsafe { std::mem::transmute::<i64, i64>(value) }
    }

    /// Writing program / tool version (index into this archive's `stringtable`).
    #[inline]
    pub fn builder_idx(&self) -> u64 {
        let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 352, 40);
        unsafe { std::mem::transmute::<u64, u64>(value) }
    }

}

impl std::fmt::Debug for ExtHeader {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.debug_struct("ExtHeader")
            .field("parent_schema_hash", &self.parent_schema_hash())
            .field("parent_node_count", &self.parent_node_count())
            .field("parent_way_count", &self.parent_way_count())
            .field("parent_relation_count", &self.parent_relation_count())
            .field("parent_tags_count", &self.parent_tags_count())
            .field("parent_stringtable_len", &self.parent_stringtable_len())
            .field("parent_replication_sequence_number", &self.parent_replication_sequence_number())
            .field("builder_idx", &self.builder_idx())
            .finish()
    }
}

impl std::cmp::PartialEq for ExtHeader {
    #[inline]
    fn eq(&self, other: &Self) -> bool {
        self.parent_schema_hash() == other.parent_schema_hash() &&        self.parent_node_count() == other.parent_node_count() &&        self.parent_way_count() == other.parent_way_count() &&        self.parent_relation_count() == other.parent_relation_count() &&        self.parent_tags_count() == other.parent_tags_count() &&        self.parent_stringtable_len() == other.parent_stringtable_len() &&        self.parent_replication_sequence_number() == other.parent_replication_sequence_number() &&        self.builder_idx() == other.builder_idx()     }
}

impl ExtHeader {
    /// Hash of the parent's embedded schema bytes (`osm.flatdata`).
    #[inline]
    #[allow(missing_docs)]
    pub fn set_parent_schema_hash(&mut self, value: u64) {
        flatdata_write_bytes!(u64; value, self.data, 0, 64)
    }

    /// Parent vector lengths at build time (cheap; catches rebuilds/reorders).
    #[inline]
    #[allow(missing_docs)]
    pub fn set_parent_node_count(&mut self, value: u64) {
        flatdata_write_bytes!(u64; value, self.data, 64, 40)
    }

    #[inline]
    #[allow(missing_docs)]
    pub fn set_parent_way_count(&mut self, value: u64) {
        flatdata_write_bytes!(u64; value, self.data, 104, 40)
    }

    #[inline]
    #[allow(missing_docs)]
    pub fn set_parent_relation_count(&mut self, value: u64) {
        flatdata_write_bytes!(u64; value, self.data, 144, 40)
    }

    #[inline]
    #[allow(missing_docs)]
    pub fn set_parent_tags_count(&mut self, value: u64) {
        flatdata_write_bytes!(u64; value, self.data, 184, 40)
    }

    #[inline]
    #[allow(missing_docs)]
    pub fn set_parent_stringtable_len(&mut self, value: u64) {
        flatdata_write_bytes!(u64; value, self.data, 224, 64)
    }

    /// Parent replication sequence number, or 0 if absent.
    #[inline]
    #[allow(missing_docs)]
    pub fn set_parent_replication_sequence_number(&mut self, value: i64) {
        flatdata_write_bytes!(i64; value, self.data, 288, 64)
    }

    /// Writing program / tool version (index into this archive's `stringtable`).
    #[inline]
    #[allow(missing_docs)]
    pub fn set_builder_idx(&mut self, value: u64) {
        flatdata_write_bytes!(u64; value, self.data, 352, 40)
    }


    /// Copies the data from `other` into this struct.
    #[inline]
    pub fn fill_from(&mut self, other: &ExtHeader) {
        self.set_parent_schema_hash(other.parent_schema_hash());
        self.set_parent_node_count(other.parent_node_count());
        self.set_parent_way_count(other.parent_way_count());
        self.set_parent_relation_count(other.parent_relation_count());
        self.set_parent_tags_count(other.parent_tags_count());
        self.set_parent_stringtable_len(other.parent_stringtable_len());
        self.set_parent_replication_sequence_number(other.parent_replication_sequence_number());
        self.set_builder_idx(other.builder_idx());
    }
}
/// A distinct OSM key. Entries in `keys` are sorted by key **string** (not by
/// `key_idx`), so a key can be found by binary search / prefix scan.
#[repr(transparent)]
pub struct KeyEntry {
    data: [u8; 25],
}

impl KeyEntry {
    /// Unsafe since the struct might not be self-contained
    pub unsafe fn new_unchecked( ) -> Self {
        Self{data : [0; 25]}
    }
}

impl flatdata::Struct for KeyEntry {
    unsafe fn create_unchecked( ) -> Self {
        Self{data : [0; 25]}
    }

    const SIZE_IN_BYTES: usize = 25;
    const IS_OVERLAPPING_WITH_NEXT : bool = true;
}

impl flatdata::Overlap for KeyEntry {}

impl KeyEntry {
    /// Key string, index into the parent `Osm.stringtable`.
    #[inline]
    pub fn key_idx(&self) -> u64 {
        let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 0, 40);
        unsafe { std::mem::transmute::<u64, u64>(value) }
    }

    /// Number of entities carrying this key, split by type (O(1) key stats).
/// A key's total is not derivable from value postings without summing, so
/// it is stored; OSM keys are unique per object, so no double counting.
    #[inline]
    pub fn count_nodes(&self) -> u64 {
        let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 40, 40);
        unsafe { std::mem::transmute::<u64, u64>(value) }
    }

    #[inline]
    pub fn count_ways(&self) -> u64 {
        let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 80, 40);
        unsafe { std::mem::transmute::<u64, u64>(value) }
    }

    #[inline]
    pub fn count_relations(&self) -> u64 {
        let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 120, 40);
        unsafe { std::mem::transmute::<u64, u64>(value) }
    }

    /// First element of the range [`values`].
    ///
    /// [`values`]: #method.values
    #[inline]
    pub fn value_first_idx(&self) -> u64 {
        let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 160, 40);
        unsafe { std::mem::transmute::<u64, u64>(value) }
    }

    /// Range of this key's distinct values in `values`.
    #[inline]
    pub fn values(&self) -> std::ops::Range<u64> {
        let start = flatdata_read_bytes!(u64, self.data.as_ptr(), 160, 40);
        let end = flatdata_read_bytes!(u64, self.data.as_ptr(), 160 + 25 * 8, 40);
        start..end
    }

}

impl std::fmt::Debug for KeyEntry {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.debug_struct("KeyEntry")
            .field("key_idx", &self.key_idx())
            .field("count_nodes", &self.count_nodes())
            .field("count_ways", &self.count_ways())
            .field("count_relations", &self.count_relations())
            .field("value_first_idx", &self.value_first_idx())
            .finish()
    }
}

impl std::cmp::PartialEq for KeyEntry {
    #[inline]
    fn eq(&self, other: &Self) -> bool {
        self.key_idx() == other.key_idx() &&        self.count_nodes() == other.count_nodes() &&        self.count_ways() == other.count_ways() &&        self.count_relations() == other.count_relations() &&        self.value_first_idx() == other.value_first_idx()     }
}

impl KeyEntry {
    /// Key string, index into the parent `Osm.stringtable`.
    #[inline]
    #[allow(missing_docs)]
    pub fn set_key_idx(&mut self, value: u64) {
        flatdata_write_bytes!(u64; value, self.data, 0, 40)
    }

    /// Number of entities carrying this key, split by type (O(1) key stats).
/// A key's total is not derivable from value postings without summing, so
/// it is stored; OSM keys are unique per object, so no double counting.
    #[inline]
    #[allow(missing_docs)]
    pub fn set_count_nodes(&mut self, value: u64) {
        flatdata_write_bytes!(u64; value, self.data, 40, 40)
    }

    #[inline]
    #[allow(missing_docs)]
    pub fn set_count_ways(&mut self, value: u64) {
        flatdata_write_bytes!(u64; value, self.data, 80, 40)
    }

    #[inline]
    #[allow(missing_docs)]
    pub fn set_count_relations(&mut self, value: u64) {
        flatdata_write_bytes!(u64; value, self.data, 120, 40)
    }

    /// First element of the range [`values`].
    ///
    /// [`values`]: struct.KeyEntryRef.html#method.values
    #[inline]
    #[allow(missing_docs)]
    pub fn set_value_first_idx(&mut self, value: u64) {
        flatdata_write_bytes!(u64; value, self.data, 160, 40)
    }


    /// Copies the data from `other` into this struct.
    #[inline]
    pub fn fill_from(&mut self, other: &KeyEntry) {
        self.set_key_idx(other.key_idx());
        self.set_count_nodes(other.count_nodes());
        self.set_count_ways(other.count_ways());
        self.set_count_relations(other.count_relations());
        self.set_value_first_idx(other.value_first_idx());
    }
}
/// A distinct value for a given key. Within one key's value range, entries are
/// sorted by value **string**. Per-(key,value) per-type counts are NOT stored:
/// they equal the corresponding postings range length.
#[repr(transparent)]
pub struct ValueEntry {
    data: [u8; 20],
}

impl ValueEntry {
    /// Unsafe since the struct might not be self-contained
    pub unsafe fn new_unchecked( ) -> Self {
        Self{data : [0; 20]}
    }
}

impl flatdata::Struct for ValueEntry {
    unsafe fn create_unchecked( ) -> Self {
        Self{data : [0; 20]}
    }

    const SIZE_IN_BYTES: usize = 20;
    const IS_OVERLAPPING_WITH_NEXT : bool = true;
}

impl flatdata::Overlap for ValueEntry {}

impl ValueEntry {
    /// Value string, index into the parent `Osm.stringtable`.
    #[inline]
    pub fn value_idx(&self) -> u64 {
        let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 0, 40);
        unsafe { std::mem::transmute::<u64, u64>(value) }
    }

    /// First element of the range [`node_post`].
    ///
    /// [`node_post`]: #method.node_post
    #[inline]
    pub fn node_first_idx(&self) -> u64 {
        let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 40, 40);
        unsafe { std::mem::transmute::<u64, u64>(value) }
    }

    /// Postings of entities having this exact (key,value), one range per type.
/// Postings are ascending parent indices == spatial (SFC) order, so they
/// merge-join with bbox ranges and with each other.
    #[inline]
    pub fn node_post(&self) -> std::ops::Range<u64> {
        let start = flatdata_read_bytes!(u64, self.data.as_ptr(), 40, 40);
        let end = flatdata_read_bytes!(u64, self.data.as_ptr(), 40 + 20 * 8, 40);
        start..end
    }

    /// First element of the range [`way_post`].
    ///
    /// [`way_post`]: #method.way_post
    #[inline]
    pub fn way_first_idx(&self) -> u64 {
        let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 80, 40);
        unsafe { std::mem::transmute::<u64, u64>(value) }
    }

    #[inline]
    pub fn way_post(&self) -> std::ops::Range<u64> {
        let start = flatdata_read_bytes!(u64, self.data.as_ptr(), 80, 40);
        let end = flatdata_read_bytes!(u64, self.data.as_ptr(), 80 + 20 * 8, 40);
        start..end
    }

    /// First element of the range [`rel_post`].
    ///
    /// [`rel_post`]: #method.rel_post
    #[inline]
    pub fn rel_first_idx(&self) -> u64 {
        let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 120, 40);
        unsafe { std::mem::transmute::<u64, u64>(value) }
    }

    #[inline]
    pub fn rel_post(&self) -> std::ops::Range<u64> {
        let start = flatdata_read_bytes!(u64, self.data.as_ptr(), 120, 40);
        let end = flatdata_read_bytes!(u64, self.data.as_ptr(), 120 + 20 * 8, 40);
        start..end
    }

}

impl std::fmt::Debug for ValueEntry {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.debug_struct("ValueEntry")
            .field("value_idx", &self.value_idx())
            .field("node_first_idx", &self.node_first_idx())
            .field("way_first_idx", &self.way_first_idx())
            .field("rel_first_idx", &self.rel_first_idx())
            .finish()
    }
}

impl std::cmp::PartialEq for ValueEntry {
    #[inline]
    fn eq(&self, other: &Self) -> bool {
        self.value_idx() == other.value_idx() &&        self.node_first_idx() == other.node_first_idx() &&        self.way_first_idx() == other.way_first_idx() &&        self.rel_first_idx() == other.rel_first_idx()     }
}

impl ValueEntry {
    /// Value string, index into the parent `Osm.stringtable`.
    #[inline]
    #[allow(missing_docs)]
    pub fn set_value_idx(&mut self, value: u64) {
        flatdata_write_bytes!(u64; value, self.data, 0, 40)
    }

    /// First element of the range [`node_post`].
    ///
    /// [`node_post`]: struct.ValueEntryRef.html#method.node_post
    #[inline]
    #[allow(missing_docs)]
    pub fn set_node_first_idx(&mut self, value: u64) {
        flatdata_write_bytes!(u64; value, self.data, 40, 40)
    }

    /// First element of the range [`way_post`].
    ///
    /// [`way_post`]: struct.ValueEntryRef.html#method.way_post
    #[inline]
    #[allow(missing_docs)]
    pub fn set_way_first_idx(&mut self, value: u64) {
        flatdata_write_bytes!(u64; value, self.data, 80, 40)
    }

    /// First element of the range [`rel_post`].
    ///
    /// [`rel_post`]: struct.ValueEntryRef.html#method.rel_post
    #[inline]
    #[allow(missing_docs)]
    pub fn set_rel_first_idx(&mut self, value: u64) {
        flatdata_write_bytes!(u64; value, self.data, 120, 40)
    }


    /// Copies the data from `other` into this struct.
    #[inline]
    pub fn fill_from(&mut self, other: &ValueEntry) {
        self.set_value_idx(other.value_idx());
        self.set_node_first_idx(other.node_first_idx());
        self.set_way_first_idx(other.way_first_idx());
        self.set_rel_first_idx(other.rel_first_idx());
    }
}
/// A reference into the parent `nodes` / `ways` / `relations` vector.
#[repr(transparent)]
#[derive(Clone)]
pub struct Ref {
    data: [u8; 5],
}

impl Ref {
    /// Unsafe since the struct might not be self-contained
    pub unsafe fn new_unchecked( ) -> Self {
        Self{data : [0; 5]}
    }
}

impl flatdata::Struct for Ref {
    unsafe fn create_unchecked( ) -> Self {
        Self{data : [0; 5]}
    }

    const SIZE_IN_BYTES: usize = 5;
    const IS_OVERLAPPING_WITH_NEXT : bool = false;
}

impl Ref {
    pub fn new( ) -> Self {
        Self{data : [0; 5]}
    }

    /// Create reference from byte array of matching size
    pub fn from_bytes(data: &[u8; 5]) -> &Self {
        // Safety: This is safe since Ref is repr(transparent)
        unsafe{ std::mem::transmute( data ) }
    }

    /// Create reference from byte array of matching size
    pub fn from_bytes_mut(data: &mut [u8; 5]) -> &mut Self {
        // Safety: This is safe since Ref is repr(transparent)
        unsafe{ std::mem::transmute( data ) }
    }

    /// Create reference from byte array
    pub fn from_bytes_slice(data: &[u8]) -> Result<&Self, flatdata::ResourceStorageError> {
        // We cannot rely on TryFrom here, since it does not yet support > 33 bytes
        if data.len() < 5 {
            assert_eq!(data.len(), 5);
            return Err(flatdata::ResourceStorageError::UnexpectedDataSize);
        }
        let ptr = data.as_ptr() as *const [u8; 5];
        // Safety: We checked length before
        Ok(Self::from_bytes(unsafe { &*ptr }))
    }

    /// Create reference from byte array
    pub fn from_bytes_slice_mut(data: &mut [u8]) -> Result<&mut Self, flatdata::ResourceStorageError> {
        // We cannot rely on TryFrom here, since it does not yet support > 33 bytes
        if data.len() < 5 {
            assert_eq!(data.len(), 5);
            return Err(flatdata::ResourceStorageError::UnexpectedDataSize);
        }
        let ptr = data.as_ptr() as *mut [u8; 5];
        // Safety: We checked length before
        Ok(Self::from_bytes_mut(unsafe { &mut *ptr }))
    }

    pub fn as_bytes(&self) -> &[u8; 5] {
        &self.data
    }
}

impl Default for Ref {
    fn default( ) -> Self {
        Self::new( )
    }
}

unsafe impl flatdata::NoOverlap for Ref {}

impl Ref {
    #[inline]
    pub fn value(&self) -> u64 {
        let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 0, 40);
        unsafe { std::mem::transmute::<u64, u64>(value) }
    }

}

impl std::fmt::Debug for Ref {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.debug_struct("Ref")
            .field("value", &self.value())
            .finish()
    }
}

impl std::cmp::PartialEq for Ref {
    #[inline]
    fn eq(&self, other: &Self) -> bool {
        self.value() == other.value()     }
}

impl Ref {
    #[inline]
    #[allow(missing_docs)]
    pub fn set_value(&mut self, value: u64) {
        flatdata_write_bytes!(u64; value, self.data, 0, 40)
    }


    /// Copies the data from `other` into this struct.
    #[inline]
    pub fn fill_from(&mut self, other: &Ref) {
        self.set_value(other.value());
    }
}
/// Generic 1:n range holder, one per parent entity, parallel to a parent vector.
#[repr(transparent)]
pub struct Range {
    data: [u8; 5],
}

impl Range {
    /// Unsafe since the struct might not be self-contained
    pub unsafe fn new_unchecked( ) -> Self {
        Self{data : [0; 5]}
    }
}

impl flatdata::Struct for Range {
    unsafe fn create_unchecked( ) -> Self {
        Self{data : [0; 5]}
    }

    const SIZE_IN_BYTES: usize = 5;
    const IS_OVERLAPPING_WITH_NEXT : bool = true;
}

impl flatdata::Overlap for Range {}

impl Range {
    /// First element of the range [`post`].
    ///
    /// [`post`]: #method.post
    #[inline]
    pub fn first_idx(&self) -> u64 {
        let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 0, 40);
        unsafe { std::mem::transmute::<u64, u64>(value) }
    }

    #[inline]
    pub fn post(&self) -> std::ops::Range<u64> {
        let start = flatdata_read_bytes!(u64, self.data.as_ptr(), 0, 40);
        let end = flatdata_read_bytes!(u64, self.data.as_ptr(), 0 + 5 * 8, 40);
        start..end
    }

}

impl std::fmt::Debug for Range {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.debug_struct("Range")
            .field("first_idx", &self.first_idx())
            .finish()
    }
}

impl std::cmp::PartialEq for Range {
    #[inline]
    fn eq(&self, other: &Self) -> bool {
        self.first_idx() == other.first_idx()     }
}

impl Range {
    /// First element of the range [`post`].
    ///
    /// [`post`]: struct.RangeRef.html#method.post
    #[inline]
    #[allow(missing_docs)]
    pub fn set_first_idx(&mut self, value: u64) {
        flatdata_write_bytes!(u64; value, self.data, 0, 40)
    }


    /// Copies the data from `other` into this struct.
    #[inline]
    pub fn fill_from(&mut self, other: &Range) {
        self.set_first_idx(other.first_idx());
    }
}



/// Inverted tag index and taginfo histograms.
#[derive(Clone)]
pub struct Taginfo {
    _storage: flatdata::StorageHandle,
    keys : &'static [super::osm_ext::KeyEntry],
    values : &'static [super::osm_ext::ValueEntry],
    node_post : &'static [super::osm_ext::Ref],
    way_post : &'static [super::osm_ext::Ref],
    rel_post : &'static [super::osm_ext::Ref],
}

impl Taginfo {
    fn signature_name(archive_name: &str) -> String {
        format!("{}.archive", archive_name)
    }

    /// Distinct keys, sorted by key string. Trailing sentinel closes the last
/// key's `values` range.
    #[inline]
    pub fn keys(&self) -> &[super::osm_ext::KeyEntry] {
        self.keys
    }

    /// Distinct values, grouped by key, sorted by value string within a key.
/// Trailing sentinel closes the last value's postings ranges.
    #[inline]
    pub fn values(&self) -> &[super::osm_ext::ValueEntry] {
        self.values
    }

    /// Per-(key,value) node postings (ascending node indices).
    #[inline]
    pub fn node_post(&self) -> &[super::osm_ext::Ref] {
        self.node_post
    }

    /// Per-(key,value) way postings (ascending way indices).
    #[inline]
    pub fn way_post(&self) -> &[super::osm_ext::Ref] {
        self.way_post
    }

    /// Per-(key,value) relation postings (ascending relation indices).
    #[inline]
    pub fn rel_post(&self) -> &[super::osm_ext::Ref] {
        self.rel_post
    }

}

impl ::std::fmt::Debug for Taginfo {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct("Taginfo")
            .field("keys", &self.keys())
            .field("values", &self.values())
            .field("node_post", &self.node_post())
            .field("way_post", &self.way_post())
            .field("rel_post", &self.rel_post())
            .finish()
    }
}

impl Taginfo {
    pub fn open(storage: flatdata::StorageHandle)
        -> ::std::result::Result<Self, flatdata::ResourceStorageError>
    {
        #[allow(unused_imports)]
        use flatdata::SliceExt;
        #[allow(unused_variables)]
        use flatdata::ResourceStorageError as Error;
        // extend lifetime since Rust cannot know that we reference a cache here
        #[allow(unused_variables)]
        let extend = |x : Result<&[u8], Error>| -> Result<&'static [u8], Error> {x.map(|x| unsafe{std::mem::transmute(x)})};

        storage.read(&Self::signature_name("Taginfo"), schema::taginfo::TAGINFO)?;

        let keys = {
            use flatdata::check_resource as check;
            let max_size = None;
            let resource = extend(storage.read("keys", schema::taginfo::resources::KEYS));
            check("keys", |r| r.len(), max_size, resource.and_then(|x| <&[super::osm_ext::KeyEntry]>::from_bytes(x)))?
        };
        let values = {
            use flatdata::check_resource as check;
            let max_size = None;
            let resource = extend(storage.read("values", schema::taginfo::resources::VALUES));
            check("values", |r| r.len(), max_size, resource.and_then(|x| <&[super::osm_ext::ValueEntry]>::from_bytes(x)))?
        };
        let node_post = {
            use flatdata::check_resource as check;
            let max_size = None;
            let resource = extend(storage.read("node_post", schema::taginfo::resources::NODE_POST));
            check("node_post", |r| r.len(), max_size, resource.and_then(|x| <&[super::osm_ext::Ref]>::from_bytes(x)))?
        };
        let way_post = {
            use flatdata::check_resource as check;
            let max_size = None;
            let resource = extend(storage.read("way_post", schema::taginfo::resources::WAY_POST));
            check("way_post", |r| r.len(), max_size, resource.and_then(|x| <&[super::osm_ext::Ref]>::from_bytes(x)))?
        };
        let rel_post = {
            use flatdata::check_resource as check;
            let max_size = None;
            let resource = extend(storage.read("rel_post", schema::taginfo::resources::REL_POST));
            check("rel_post", |r| r.len(), max_size, resource.and_then(|x| <&[super::osm_ext::Ref]>::from_bytes(x)))?
        };

        Ok(Self {
            _storage: storage,
            keys,
            values,
            node_post,
            way_post,
            rel_post,
        })
    }
}

/// Builder for creating [`Taginfo`] archives.
///
///[`Taginfo`]: struct.Taginfo.html
#[derive(Clone, Debug)]
pub struct TaginfoBuilder {
    storage: flatdata::StorageHandle
}

impl TaginfoBuilder {
    #[inline]
    /// Stores [`keys`] in the archive.
    ///
    /// [`keys`]: struct.Taginfo.html#method.keys
    pub fn set_keys(&self, vector: &[super::osm_ext::KeyEntry]) -> ::std::io::Result<()> {
        use flatdata::SliceExt;
        self.storage.write("keys", schema::taginfo::resources::KEYS, vector.as_bytes())
    }

    /// Opens [`keys`] in the archive for buffered writing.
    ///
    /// Elements can be added to the vector until the [`ExternalVector::close`] method
    /// is called. To flush the data fully into the archive, this method must be called
    /// in the end.
    ///
    /// [`keys`]: struct.Taginfo.html#method.keys
    /// [`ExternalVector::close`]: flatdata/struct.ExternalVector.html#method.close
    #[inline]
    pub fn start_keys(&self) -> ::std::io::Result<flatdata::ExternalVector<super::osm_ext::KeyEntry>> {
        flatdata::create_external_vector(&*self.storage, "keys", schema::taginfo::resources::KEYS)
    }

    #[inline]
    /// Stores [`values`] in the archive.
    ///
    /// [`values`]: struct.Taginfo.html#method.values
    pub fn set_values(&self, vector: &[super::osm_ext::ValueEntry]) -> ::std::io::Result<()> {
        use flatdata::SliceExt;
        self.storage.write("values", schema::taginfo::resources::VALUES, vector.as_bytes())
    }

    /// Opens [`values`] in the archive for buffered writing.
    ///
    /// Elements can be added to the vector until the [`ExternalVector::close`] method
    /// is called. To flush the data fully into the archive, this method must be called
    /// in the end.
    ///
    /// [`values`]: struct.Taginfo.html#method.values
    /// [`ExternalVector::close`]: flatdata/struct.ExternalVector.html#method.close
    #[inline]
    pub fn start_values(&self) -> ::std::io::Result<flatdata::ExternalVector<super::osm_ext::ValueEntry>> {
        flatdata::create_external_vector(&*self.storage, "values", schema::taginfo::resources::VALUES)
    }

    #[inline]
    /// Stores [`node_post`] in the archive.
    ///
    /// [`node_post`]: struct.Taginfo.html#method.node_post
    pub fn set_node_post(&self, vector: &[super::osm_ext::Ref]) -> ::std::io::Result<()> {
        use flatdata::SliceExt;
        self.storage.write("node_post", schema::taginfo::resources::NODE_POST, vector.as_bytes())
    }

    /// Opens [`node_post`] in the archive for buffered writing.
    ///
    /// Elements can be added to the vector until the [`ExternalVector::close`] method
    /// is called. To flush the data fully into the archive, this method must be called
    /// in the end.
    ///
    /// [`node_post`]: struct.Taginfo.html#method.node_post
    /// [`ExternalVector::close`]: flatdata/struct.ExternalVector.html#method.close
    #[inline]
    pub fn start_node_post(&self) -> ::std::io::Result<flatdata::ExternalVector<super::osm_ext::Ref>> {
        flatdata::create_external_vector(&*self.storage, "node_post", schema::taginfo::resources::NODE_POST)
    }

    #[inline]
    /// Stores [`way_post`] in the archive.
    ///
    /// [`way_post`]: struct.Taginfo.html#method.way_post
    pub fn set_way_post(&self, vector: &[super::osm_ext::Ref]) -> ::std::io::Result<()> {
        use flatdata::SliceExt;
        self.storage.write("way_post", schema::taginfo::resources::WAY_POST, vector.as_bytes())
    }

    /// Opens [`way_post`] in the archive for buffered writing.
    ///
    /// Elements can be added to the vector until the [`ExternalVector::close`] method
    /// is called. To flush the data fully into the archive, this method must be called
    /// in the end.
    ///
    /// [`way_post`]: struct.Taginfo.html#method.way_post
    /// [`ExternalVector::close`]: flatdata/struct.ExternalVector.html#method.close
    #[inline]
    pub fn start_way_post(&self) -> ::std::io::Result<flatdata::ExternalVector<super::osm_ext::Ref>> {
        flatdata::create_external_vector(&*self.storage, "way_post", schema::taginfo::resources::WAY_POST)
    }

    #[inline]
    /// Stores [`rel_post`] in the archive.
    ///
    /// [`rel_post`]: struct.Taginfo.html#method.rel_post
    pub fn set_rel_post(&self, vector: &[super::osm_ext::Ref]) -> ::std::io::Result<()> {
        use flatdata::SliceExt;
        self.storage.write("rel_post", schema::taginfo::resources::REL_POST, vector.as_bytes())
    }

    /// Opens [`rel_post`] in the archive for buffered writing.
    ///
    /// Elements can be added to the vector until the [`ExternalVector::close`] method
    /// is called. To flush the data fully into the archive, this method must be called
    /// in the end.
    ///
    /// [`rel_post`]: struct.Taginfo.html#method.rel_post
    /// [`ExternalVector::close`]: flatdata/struct.ExternalVector.html#method.close
    #[inline]
    pub fn start_rel_post(&self) -> ::std::io::Result<flatdata::ExternalVector<super::osm_ext::Ref>> {
        flatdata::create_external_vector(&*self.storage, "rel_post", schema::taginfo::resources::REL_POST)
    }

}

impl TaginfoBuilder {
    pub fn new(
        storage: flatdata::StorageHandle,
    ) -> Result<Self, flatdata::ResourceStorageError> {
        flatdata::create_archive("Taginfo", schema::taginfo::TAGINFO, &storage)?;
        Ok(Self { storage })
    }
}




/// Reverse references. Each `*_range` vector is parallel to a parent entity
/// vector (plus a trailing sentinel) and slices the matching postings vector.
#[derive(Clone)]
pub struct Backrefs {
    _storage: flatdata::StorageHandle,
    node_ways_range : &'static [super::osm_ext::Range],
    ways_of_node : &'static [super::osm_ext::Ref],
    node_rels_range : &'static [super::osm_ext::Range],
    rels_of_node : &'static [super::osm_ext::Ref],
    way_rels_range : &'static [super::osm_ext::Range],
    rels_of_way : &'static [super::osm_ext::Ref],
    rel_rels_range : &'static [super::osm_ext::Range],
    rels_of_rel : &'static [super::osm_ext::Ref],
}

impl Backrefs {
    fn signature_name(archive_name: &str) -> String {
        format!("{}.archive", archive_name)
    }

    /// Parallel to parent `nodes`: ways referencing each node.
    #[inline]
    pub fn node_ways_range(&self) -> &[super::osm_ext::Range] {
        self.node_ways_range
    }

    /// Way indices, grouped by referenced node, ascending.
    #[inline]
    pub fn ways_of_node(&self) -> &[super::osm_ext::Ref] {
        self.ways_of_node
    }

    /// Parallel to parent `nodes`: relations whose members include each node.
    #[inline]
    pub fn node_rels_range(&self) -> &[super::osm_ext::Range] {
        self.node_rels_range
    }

    #[inline]
    pub fn rels_of_node(&self) -> &[super::osm_ext::Ref] {
        self.rels_of_node
    }

    /// Parallel to parent `ways`: relations whose members include each way.
    #[inline]
    pub fn way_rels_range(&self) -> &[super::osm_ext::Range] {
        self.way_rels_range
    }

    #[inline]
    pub fn rels_of_way(&self) -> &[super::osm_ext::Ref] {
        self.rels_of_way
    }

    /// Parallel to parent `relations`: relations whose members include a relation.
    #[inline]
    pub fn rel_rels_range(&self) -> &[super::osm_ext::Range] {
        self.rel_rels_range
    }

    #[inline]
    pub fn rels_of_rel(&self) -> &[super::osm_ext::Ref] {
        self.rels_of_rel
    }

}

impl ::std::fmt::Debug for Backrefs {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct("Backrefs")
            .field("node_ways_range", &self.node_ways_range())
            .field("ways_of_node", &self.ways_of_node())
            .field("node_rels_range", &self.node_rels_range())
            .field("rels_of_node", &self.rels_of_node())
            .field("way_rels_range", &self.way_rels_range())
            .field("rels_of_way", &self.rels_of_way())
            .field("rel_rels_range", &self.rel_rels_range())
            .field("rels_of_rel", &self.rels_of_rel())
            .finish()
    }
}

impl Backrefs {
    pub fn open(storage: flatdata::StorageHandle)
        -> ::std::result::Result<Self, flatdata::ResourceStorageError>
    {
        #[allow(unused_imports)]
        use flatdata::SliceExt;
        #[allow(unused_variables)]
        use flatdata::ResourceStorageError as Error;
        // extend lifetime since Rust cannot know that we reference a cache here
        #[allow(unused_variables)]
        let extend = |x : Result<&[u8], Error>| -> Result<&'static [u8], Error> {x.map(|x| unsafe{std::mem::transmute(x)})};

        storage.read(&Self::signature_name("Backrefs"), schema::backrefs::BACKREFS)?;

        let node_ways_range = {
            use flatdata::check_resource as check;
            let max_size = None;
            let resource = extend(storage.read("node_ways_range", schema::backrefs::resources::NODE_WAYS_RANGE));
            check("node_ways_range", |r| r.len(), max_size, resource.and_then(|x| <&[super::osm_ext::Range]>::from_bytes(x)))?
        };
        let ways_of_node = {
            use flatdata::check_resource as check;
            let max_size = None;
            let resource = extend(storage.read("ways_of_node", schema::backrefs::resources::WAYS_OF_NODE));
            check("ways_of_node", |r| r.len(), max_size, resource.and_then(|x| <&[super::osm_ext::Ref]>::from_bytes(x)))?
        };
        let node_rels_range = {
            use flatdata::check_resource as check;
            let max_size = None;
            let resource = extend(storage.read("node_rels_range", schema::backrefs::resources::NODE_RELS_RANGE));
            check("node_rels_range", |r| r.len(), max_size, resource.and_then(|x| <&[super::osm_ext::Range]>::from_bytes(x)))?
        };
        let rels_of_node = {
            use flatdata::check_resource as check;
            let max_size = None;
            let resource = extend(storage.read("rels_of_node", schema::backrefs::resources::RELS_OF_NODE));
            check("rels_of_node", |r| r.len(), max_size, resource.and_then(|x| <&[super::osm_ext::Ref]>::from_bytes(x)))?
        };
        let way_rels_range = {
            use flatdata::check_resource as check;
            let max_size = None;
            let resource = extend(storage.read("way_rels_range", schema::backrefs::resources::WAY_RELS_RANGE));
            check("way_rels_range", |r| r.len(), max_size, resource.and_then(|x| <&[super::osm_ext::Range]>::from_bytes(x)))?
        };
        let rels_of_way = {
            use flatdata::check_resource as check;
            let max_size = None;
            let resource = extend(storage.read("rels_of_way", schema::backrefs::resources::RELS_OF_WAY));
            check("rels_of_way", |r| r.len(), max_size, resource.and_then(|x| <&[super::osm_ext::Ref]>::from_bytes(x)))?
        };
        let rel_rels_range = {
            use flatdata::check_resource as check;
            let max_size = None;
            let resource = extend(storage.read("rel_rels_range", schema::backrefs::resources::REL_RELS_RANGE));
            check("rel_rels_range", |r| r.len(), max_size, resource.and_then(|x| <&[super::osm_ext::Range]>::from_bytes(x)))?
        };
        let rels_of_rel = {
            use flatdata::check_resource as check;
            let max_size = None;
            let resource = extend(storage.read("rels_of_rel", schema::backrefs::resources::RELS_OF_REL));
            check("rels_of_rel", |r| r.len(), max_size, resource.and_then(|x| <&[super::osm_ext::Ref]>::from_bytes(x)))?
        };

        Ok(Self {
            _storage: storage,
            node_ways_range,
            ways_of_node,
            node_rels_range,
            rels_of_node,
            way_rels_range,
            rels_of_way,
            rel_rels_range,
            rels_of_rel,
        })
    }
}

/// Builder for creating [`Backrefs`] archives.
///
///[`Backrefs`]: struct.Backrefs.html
#[derive(Clone, Debug)]
pub struct BackrefsBuilder {
    storage: flatdata::StorageHandle
}

impl BackrefsBuilder {
    #[inline]
    /// Stores [`node_ways_range`] in the archive.
    ///
    /// [`node_ways_range`]: struct.Backrefs.html#method.node_ways_range
    pub fn set_node_ways_range(&self, vector: &[super::osm_ext::Range]) -> ::std::io::Result<()> {
        use flatdata::SliceExt;
        self.storage.write("node_ways_range", schema::backrefs::resources::NODE_WAYS_RANGE, vector.as_bytes())
    }

    /// Opens [`node_ways_range`] in the archive for buffered writing.
    ///
    /// Elements can be added to the vector until the [`ExternalVector::close`] method
    /// is called. To flush the data fully into the archive, this method must be called
    /// in the end.
    ///
    /// [`node_ways_range`]: struct.Backrefs.html#method.node_ways_range
    /// [`ExternalVector::close`]: flatdata/struct.ExternalVector.html#method.close
    #[inline]
    pub fn start_node_ways_range(&self) -> ::std::io::Result<flatdata::ExternalVector<super::osm_ext::Range>> {
        flatdata::create_external_vector(&*self.storage, "node_ways_range", schema::backrefs::resources::NODE_WAYS_RANGE)
    }

    #[inline]
    /// Stores [`ways_of_node`] in the archive.
    ///
    /// [`ways_of_node`]: struct.Backrefs.html#method.ways_of_node
    pub fn set_ways_of_node(&self, vector: &[super::osm_ext::Ref]) -> ::std::io::Result<()> {
        use flatdata::SliceExt;
        self.storage.write("ways_of_node", schema::backrefs::resources::WAYS_OF_NODE, vector.as_bytes())
    }

    /// Opens [`ways_of_node`] in the archive for buffered writing.
    ///
    /// Elements can be added to the vector until the [`ExternalVector::close`] method
    /// is called. To flush the data fully into the archive, this method must be called
    /// in the end.
    ///
    /// [`ways_of_node`]: struct.Backrefs.html#method.ways_of_node
    /// [`ExternalVector::close`]: flatdata/struct.ExternalVector.html#method.close
    #[inline]
    pub fn start_ways_of_node(&self) -> ::std::io::Result<flatdata::ExternalVector<super::osm_ext::Ref>> {
        flatdata::create_external_vector(&*self.storage, "ways_of_node", schema::backrefs::resources::WAYS_OF_NODE)
    }

    #[inline]
    /// Stores [`node_rels_range`] in the archive.
    ///
    /// [`node_rels_range`]: struct.Backrefs.html#method.node_rels_range
    pub fn set_node_rels_range(&self, vector: &[super::osm_ext::Range]) -> ::std::io::Result<()> {
        use flatdata::SliceExt;
        self.storage.write("node_rels_range", schema::backrefs::resources::NODE_RELS_RANGE, vector.as_bytes())
    }

    /// Opens [`node_rels_range`] in the archive for buffered writing.
    ///
    /// Elements can be added to the vector until the [`ExternalVector::close`] method
    /// is called. To flush the data fully into the archive, this method must be called
    /// in the end.
    ///
    /// [`node_rels_range`]: struct.Backrefs.html#method.node_rels_range
    /// [`ExternalVector::close`]: flatdata/struct.ExternalVector.html#method.close
    #[inline]
    pub fn start_node_rels_range(&self) -> ::std::io::Result<flatdata::ExternalVector<super::osm_ext::Range>> {
        flatdata::create_external_vector(&*self.storage, "node_rels_range", schema::backrefs::resources::NODE_RELS_RANGE)
    }

    #[inline]
    /// Stores [`rels_of_node`] in the archive.
    ///
    /// [`rels_of_node`]: struct.Backrefs.html#method.rels_of_node
    pub fn set_rels_of_node(&self, vector: &[super::osm_ext::Ref]) -> ::std::io::Result<()> {
        use flatdata::SliceExt;
        self.storage.write("rels_of_node", schema::backrefs::resources::RELS_OF_NODE, vector.as_bytes())
    }

    /// Opens [`rels_of_node`] in the archive for buffered writing.
    ///
    /// Elements can be added to the vector until the [`ExternalVector::close`] method
    /// is called. To flush the data fully into the archive, this method must be called
    /// in the end.
    ///
    /// [`rels_of_node`]: struct.Backrefs.html#method.rels_of_node
    /// [`ExternalVector::close`]: flatdata/struct.ExternalVector.html#method.close
    #[inline]
    pub fn start_rels_of_node(&self) -> ::std::io::Result<flatdata::ExternalVector<super::osm_ext::Ref>> {
        flatdata::create_external_vector(&*self.storage, "rels_of_node", schema::backrefs::resources::RELS_OF_NODE)
    }

    #[inline]
    /// Stores [`way_rels_range`] in the archive.
    ///
    /// [`way_rels_range`]: struct.Backrefs.html#method.way_rels_range
    pub fn set_way_rels_range(&self, vector: &[super::osm_ext::Range]) -> ::std::io::Result<()> {
        use flatdata::SliceExt;
        self.storage.write("way_rels_range", schema::backrefs::resources::WAY_RELS_RANGE, vector.as_bytes())
    }

    /// Opens [`way_rels_range`] in the archive for buffered writing.
    ///
    /// Elements can be added to the vector until the [`ExternalVector::close`] method
    /// is called. To flush the data fully into the archive, this method must be called
    /// in the end.
    ///
    /// [`way_rels_range`]: struct.Backrefs.html#method.way_rels_range
    /// [`ExternalVector::close`]: flatdata/struct.ExternalVector.html#method.close
    #[inline]
    pub fn start_way_rels_range(&self) -> ::std::io::Result<flatdata::ExternalVector<super::osm_ext::Range>> {
        flatdata::create_external_vector(&*self.storage, "way_rels_range", schema::backrefs::resources::WAY_RELS_RANGE)
    }

    #[inline]
    /// Stores [`rels_of_way`] in the archive.
    ///
    /// [`rels_of_way`]: struct.Backrefs.html#method.rels_of_way
    pub fn set_rels_of_way(&self, vector: &[super::osm_ext::Ref]) -> ::std::io::Result<()> {
        use flatdata::SliceExt;
        self.storage.write("rels_of_way", schema::backrefs::resources::RELS_OF_WAY, vector.as_bytes())
    }

    /// Opens [`rels_of_way`] in the archive for buffered writing.
    ///
    /// Elements can be added to the vector until the [`ExternalVector::close`] method
    /// is called. To flush the data fully into the archive, this method must be called
    /// in the end.
    ///
    /// [`rels_of_way`]: struct.Backrefs.html#method.rels_of_way
    /// [`ExternalVector::close`]: flatdata/struct.ExternalVector.html#method.close
    #[inline]
    pub fn start_rels_of_way(&self) -> ::std::io::Result<flatdata::ExternalVector<super::osm_ext::Ref>> {
        flatdata::create_external_vector(&*self.storage, "rels_of_way", schema::backrefs::resources::RELS_OF_WAY)
    }

    #[inline]
    /// Stores [`rel_rels_range`] in the archive.
    ///
    /// [`rel_rels_range`]: struct.Backrefs.html#method.rel_rels_range
    pub fn set_rel_rels_range(&self, vector: &[super::osm_ext::Range]) -> ::std::io::Result<()> {
        use flatdata::SliceExt;
        self.storage.write("rel_rels_range", schema::backrefs::resources::REL_RELS_RANGE, vector.as_bytes())
    }

    /// Opens [`rel_rels_range`] in the archive for buffered writing.
    ///
    /// Elements can be added to the vector until the [`ExternalVector::close`] method
    /// is called. To flush the data fully into the archive, this method must be called
    /// in the end.
    ///
    /// [`rel_rels_range`]: struct.Backrefs.html#method.rel_rels_range
    /// [`ExternalVector::close`]: flatdata/struct.ExternalVector.html#method.close
    #[inline]
    pub fn start_rel_rels_range(&self) -> ::std::io::Result<flatdata::ExternalVector<super::osm_ext::Range>> {
        flatdata::create_external_vector(&*self.storage, "rel_rels_range", schema::backrefs::resources::REL_RELS_RANGE)
    }

    #[inline]
    /// Stores [`rels_of_rel`] in the archive.
    ///
    /// [`rels_of_rel`]: struct.Backrefs.html#method.rels_of_rel
    pub fn set_rels_of_rel(&self, vector: &[super::osm_ext::Ref]) -> ::std::io::Result<()> {
        use flatdata::SliceExt;
        self.storage.write("rels_of_rel", schema::backrefs::resources::RELS_OF_REL, vector.as_bytes())
    }

    /// Opens [`rels_of_rel`] in the archive for buffered writing.
    ///
    /// Elements can be added to the vector until the [`ExternalVector::close`] method
    /// is called. To flush the data fully into the archive, this method must be called
    /// in the end.
    ///
    /// [`rels_of_rel`]: struct.Backrefs.html#method.rels_of_rel
    /// [`ExternalVector::close`]: flatdata/struct.ExternalVector.html#method.close
    #[inline]
    pub fn start_rels_of_rel(&self) -> ::std::io::Result<flatdata::ExternalVector<super::osm_ext::Ref>> {
        flatdata::create_external_vector(&*self.storage, "rels_of_rel", schema::backrefs::resources::RELS_OF_REL)
    }

}

impl BackrefsBuilder {
    pub fn new(
        storage: flatdata::StorageHandle,
    ) -> Result<Self, flatdata::ResourceStorageError> {
        flatdata::create_archive("Backrefs", schema::backrefs::BACKREFS, &storage)?;
        Ok(Self { storage })
    }
}




/// Sibling extension archive for an `osm.Osm` archive. Each capability is an
/// optional sub-archive, built independently (`--taginfo`, `--backrefs`).
#[derive(Clone)]
pub struct Ext {
    _storage: flatdata::StorageHandle,
    header : &'static super::osm_ext::ExtHeader,
    stringtable : flatdata::RawData<'static>,
    taginfo : Option<super::osm_ext::Taginfo
>,
    backrefs : Option<super::osm_ext::Backrefs
>,
}

impl Ext {
    fn signature_name(archive_name: &str) -> String {
        format!("{}.archive", archive_name)
    }

    /// Fingerprint of the parent archive this sidecar indexes.
    #[inline]
    pub fn header(&self) -> &super::osm_ext::ExtHeader {
        self.header
    }

    /// String storage for this archive's own metadata (e.g. builder version).
    #[inline]
    pub fn stringtable(&self) -> flatdata::RawData {
        self.stringtable
    }

    /// Inverted tag index + taginfo histograms.
    #[inline]
    pub fn taginfo(&self) -> Option<&super::osm_ext::Taginfo> {
        self.taginfo.as_ref()
    }

    /// Reverse references.
    #[inline]
    pub fn backrefs(&self) -> Option<&super::osm_ext::Backrefs> {
        self.backrefs.as_ref()
    }

}

impl ::std::fmt::Debug for Ext {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct("Ext")
            .field("header", &self.header())
            .field("stringtable", &self.stringtable())
            .field("taginfo", &self.taginfo())
            .field("backrefs", &self.backrefs())
            .finish()
    }
}

impl Ext {
    pub fn open(storage: flatdata::StorageHandle)
        -> ::std::result::Result<Self, flatdata::ResourceStorageError>
    {
        #[allow(unused_imports)]
        use flatdata::SliceExt;
        #[allow(unused_variables)]
        use flatdata::ResourceStorageError as Error;
        // extend lifetime since Rust cannot know that we reference a cache here
        #[allow(unused_variables)]
        let extend = |x : Result<&[u8], Error>| -> Result<&'static [u8], Error> {x.map(|x| unsafe{std::mem::transmute(x)})};

        storage.read(&Self::signature_name("Ext"), schema::ext::EXT)?;

        let header = {
            use flatdata::check_resource as check;
            let max_size = None;
            let resource = extend(storage.read("header", schema::ext::resources::HEADER));
            check("header", |_| 0, max_size, resource.and_then(|x| super::osm_ext::ExtHeader::from_bytes_slice(x)))?
        };
        let stringtable = {
            use flatdata::check_resource as check;
            let max_size = Some(1099511627776);
            let resource = extend(storage.read("stringtable", schema::ext::resources::STRINGTABLE));
            check("stringtable", |r| r.len(), max_size, resource.map(|x| flatdata::RawData::new(x)))?
        };
        let taginfo = {
            use flatdata::check_optional_resource as check;
            let max_size = None;
            check("taginfo", |_| 0, max_size, super::osm_ext::Taginfo::open(storage.subdir("taginfo")))?
        };
        let backrefs = {
            use flatdata::check_optional_resource as check;
            let max_size = None;
            check("backrefs", |_| 0, max_size, super::osm_ext::Backrefs::open(storage.subdir("backrefs")))?
        };

        Ok(Self {
            _storage: storage,
            header,
            stringtable,
            taginfo,
            backrefs,
        })
    }
}

/// Builder for creating [`Ext`] archives.
///
///[`Ext`]: struct.Ext.html
#[derive(Clone, Debug)]
pub struct ExtBuilder {
    storage: flatdata::StorageHandle
}

impl ExtBuilder {
    #[inline]
    /// Stores [`header`] in the archive.
    ///
    /// [`header`]: struct.Ext.html#method.header
    /// Stores [`header`] in the archive.
    pub fn set_header(&self, resource: &super::osm_ext::ExtHeader) -> ::std::io::Result<()> {
        let data = resource.as_bytes();
        self.storage.write("header", schema::ext::resources::HEADER, data)
    }

    /// Stores [`stringtable`] in the archive.
    ///
    /// [`stringtable`]: struct.Ext.html#method.stringtable
    #[inline]
    pub fn set_stringtable(&self, data: &[u8]) -> ::std::io::Result<()> {
        self.storage.write("stringtable", schema::ext::resources::STRINGTABLE, data)
    }

    /// Stores [`taginfo`] in the archive.
    ///
    /// [`taginfo`]: struct.Ext.html#method.taginfo
    #[inline]
    pub fn taginfo(&self) -> Result<super::osm_ext::TaginfoBuilder, flatdata::ResourceStorageError> {
        let storage = self.storage.subdir("taginfo");
        super::osm_ext::TaginfoBuilder::new(storage)
    }

    /// Stores [`backrefs`] in the archive.
    ///
    /// [`backrefs`]: struct.Ext.html#method.backrefs
    #[inline]
    pub fn backrefs(&self) -> Result<super::osm_ext::BackrefsBuilder, flatdata::ResourceStorageError> {
        let storage = self.storage.subdir("backrefs");
        super::osm_ext::BackrefsBuilder::new(storage)
    }

}

impl ExtBuilder {
    pub fn new(
        storage: flatdata::StorageHandle,
    ) -> Result<Self, flatdata::ResourceStorageError> {
        flatdata::create_archive("Ext", schema::ext::EXT, &storage)?;
        Ok(Self { storage })
    }
}


#[doc(hidden)]
pub mod schema {
pub mod taginfo {

pub const TAGINFO: &str = r#"namespace osm_ext {
struct KeyEntry
{
    key_idx : u64 : 40;
    count_nodes : u64 : 40;
    count_ways : u64 : 40;
    count_relations : u64 : 40;
    @range( values )
    value_first_idx : u64 : 40;
}
}

namespace osm_ext {
struct ValueEntry
{
    value_idx : u64 : 40;
    @range( node_post )
    node_first_idx : u64 : 40;
    @range( way_post )
    way_first_idx : u64 : 40;
    @range( rel_post )
    rel_first_idx : u64 : 40;
}
}

namespace osm_ext {
struct Ref
{
    value : u64 : 40;
}
}

namespace osm_ext {
const u64 INVALID_IDX = 1099511627775;
}

namespace osm_ext {
archive Taginfo
{
    keys : vector< .osm_ext.KeyEntry >;
    values : vector< .osm_ext.ValueEntry >;
    node_post : vector< .osm_ext.Ref >;
    way_post : vector< .osm_ext.Ref >;
    rel_post : vector< .osm_ext.Ref >;
}
}

"#;

pub mod resources {
pub const KEYS: &str = r#"namespace osm_ext {
struct KeyEntry
{
    key_idx : u64 : 40;
    count_nodes : u64 : 40;
    count_ways : u64 : 40;
    count_relations : u64 : 40;
    @range( values )
    value_first_idx : u64 : 40;
}
}

namespace osm_ext {
archive Taginfo
{
    keys : vector< .osm_ext.KeyEntry >;
}
}

"#;
pub const VALUES: &str = r#"namespace osm_ext {
struct ValueEntry
{
    value_idx : u64 : 40;
    @range( node_post )
    node_first_idx : u64 : 40;
    @range( way_post )
    way_first_idx : u64 : 40;
    @range( rel_post )
    rel_first_idx : u64 : 40;
}
}

namespace osm_ext {
archive Taginfo
{
    values : vector< .osm_ext.ValueEntry >;
}
}

"#;
pub const NODE_POST: &str = r#"namespace osm_ext {
struct Ref
{
    value : u64 : 40;
}
}

namespace osm_ext {
archive Taginfo
{
    node_post : vector< .osm_ext.Ref >;
}
}

"#;
pub const WAY_POST: &str = r#"namespace osm_ext {
struct Ref
{
    value : u64 : 40;
}
}

namespace osm_ext {
archive Taginfo
{
    way_post : vector< .osm_ext.Ref >;
}
}

"#;
pub const REL_POST: &str = r#"namespace osm_ext {
struct Ref
{
    value : u64 : 40;
}
}

namespace osm_ext {
archive Taginfo
{
    rel_post : vector< .osm_ext.Ref >;
}
}

"#;
}
}
pub mod backrefs {

pub const BACKREFS: &str = r#"namespace osm_ext {
struct Range
{
    @range( post )
    first_idx : u64 : 40;
}
}

namespace osm_ext {
struct Ref
{
    value : u64 : 40;
}
}

namespace osm_ext {
const u64 INVALID_IDX = 1099511627775;
}

namespace osm_ext {
archive Backrefs
{
    node_ways_range : vector< .osm_ext.Range >;
    ways_of_node : vector< .osm_ext.Ref >;
    node_rels_range : vector< .osm_ext.Range >;
    rels_of_node : vector< .osm_ext.Ref >;
    way_rels_range : vector< .osm_ext.Range >;
    rels_of_way : vector< .osm_ext.Ref >;
    rel_rels_range : vector< .osm_ext.Range >;
    rels_of_rel : vector< .osm_ext.Ref >;
}
}

"#;

pub mod resources {
pub const NODE_WAYS_RANGE: &str = r#"namespace osm_ext {
struct Range
{
    @range( post )
    first_idx : u64 : 40;
}
}

namespace osm_ext {
archive Backrefs
{
    node_ways_range : vector< .osm_ext.Range >;
}
}

"#;
pub const WAYS_OF_NODE: &str = r#"namespace osm_ext {
struct Ref
{
    value : u64 : 40;
}
}

namespace osm_ext {
archive Backrefs
{
    ways_of_node : vector< .osm_ext.Ref >;
}
}

"#;
pub const NODE_RELS_RANGE: &str = r#"namespace osm_ext {
struct Range
{
    @range( post )
    first_idx : u64 : 40;
}
}

namespace osm_ext {
archive Backrefs
{
    node_rels_range : vector< .osm_ext.Range >;
}
}

"#;
pub const RELS_OF_NODE: &str = r#"namespace osm_ext {
struct Ref
{
    value : u64 : 40;
}
}

namespace osm_ext {
archive Backrefs
{
    rels_of_node : vector< .osm_ext.Ref >;
}
}

"#;
pub const WAY_RELS_RANGE: &str = r#"namespace osm_ext {
struct Range
{
    @range( post )
    first_idx : u64 : 40;
}
}

namespace osm_ext {
archive Backrefs
{
    way_rels_range : vector< .osm_ext.Range >;
}
}

"#;
pub const RELS_OF_WAY: &str = r#"namespace osm_ext {
struct Ref
{
    value : u64 : 40;
}
}

namespace osm_ext {
archive Backrefs
{
    rels_of_way : vector< .osm_ext.Ref >;
}
}

"#;
pub const REL_RELS_RANGE: &str = r#"namespace osm_ext {
struct Range
{
    @range( post )
    first_idx : u64 : 40;
}
}

namespace osm_ext {
archive Backrefs
{
    rel_rels_range : vector< .osm_ext.Range >;
}
}

"#;
pub const RELS_OF_REL: &str = r#"namespace osm_ext {
struct Ref
{
    value : u64 : 40;
}
}

namespace osm_ext {
archive Backrefs
{
    rels_of_rel : vector< .osm_ext.Ref >;
}
}

"#;
}
}
pub mod ext {

pub const EXT: &str = r#"namespace osm_ext {
struct ExtHeader
{
    parent_schema_hash : u64 : 64;
    parent_node_count : u64 : 40;
    parent_way_count : u64 : 40;
    parent_relation_count : u64 : 40;
    parent_tags_count : u64 : 40;
    parent_stringtable_len : u64 : 64;
    parent_replication_sequence_number : i64 : 64;
    builder_idx : u64 : 40;
}
}

namespace osm_ext {
struct KeyEntry
{
    key_idx : u64 : 40;
    count_nodes : u64 : 40;
    count_ways : u64 : 40;
    count_relations : u64 : 40;
    @range( values )
    value_first_idx : u64 : 40;
}
}

namespace osm_ext {
struct ValueEntry
{
    value_idx : u64 : 40;
    @range( node_post )
    node_first_idx : u64 : 40;
    @range( way_post )
    way_first_idx : u64 : 40;
    @range( rel_post )
    rel_first_idx : u64 : 40;
}
}

namespace osm_ext {
struct Ref
{
    value : u64 : 40;
}
}

namespace osm_ext {
const u64 INVALID_IDX = 1099511627775;
}

namespace osm_ext {
archive Taginfo
{
    keys : vector< .osm_ext.KeyEntry >;
    values : vector< .osm_ext.ValueEntry >;
    node_post : vector< .osm_ext.Ref >;
    way_post : vector< .osm_ext.Ref >;
    rel_post : vector< .osm_ext.Ref >;
}
}

namespace osm_ext {
struct Range
{
    @range( post )
    first_idx : u64 : 40;
}
}

namespace osm_ext {
archive Backrefs
{
    node_ways_range : vector< .osm_ext.Range >;
    ways_of_node : vector< .osm_ext.Ref >;
    node_rels_range : vector< .osm_ext.Range >;
    rels_of_node : vector< .osm_ext.Ref >;
    way_rels_range : vector< .osm_ext.Range >;
    rels_of_way : vector< .osm_ext.Ref >;
    rel_rels_range : vector< .osm_ext.Range >;
    rels_of_rel : vector< .osm_ext.Ref >;
}
}

namespace osm_ext {
archive Ext
{
    @explicit_reference( .osm_ext.ExtHeader.builder_idx, .osm_ext.Ext.stringtable )
    header : .osm_ext.ExtHeader;
    stringtable : raw_data;
    @optional
    taginfo : archive .osm_ext.Taginfo;
    @optional
    backrefs : archive .osm_ext.Backrefs;
}
}

"#;

pub mod resources {
pub const HEADER: &str = r#"namespace osm_ext {
struct ExtHeader
{
    parent_schema_hash : u64 : 64;
    parent_node_count : u64 : 40;
    parent_way_count : u64 : 40;
    parent_relation_count : u64 : 40;
    parent_tags_count : u64 : 40;
    parent_stringtable_len : u64 : 64;
    parent_replication_sequence_number : i64 : 64;
    builder_idx : u64 : 40;
}
}

namespace osm_ext {
archive Ext
{
    @explicit_reference( .osm_ext.ExtHeader.builder_idx, .osm_ext.Ext.stringtable )
    header : .osm_ext.ExtHeader;
}
}

"#;
pub const STRINGTABLE: &str = r#"namespace osm_ext {
archive Ext
{
    stringtable : raw_data;
}
}

"#;
pub const TAGINFO: &str = r#"namespace osm_ext {
struct KeyEntry
{
    key_idx : u64 : 40;
    count_nodes : u64 : 40;
    count_ways : u64 : 40;
    count_relations : u64 : 40;
    @range( values )
    value_first_idx : u64 : 40;
}
}

namespace osm_ext {
struct ValueEntry
{
    value_idx : u64 : 40;
    @range( node_post )
    node_first_idx : u64 : 40;
    @range( way_post )
    way_first_idx : u64 : 40;
    @range( rel_post )
    rel_first_idx : u64 : 40;
}
}

namespace osm_ext {
struct Ref
{
    value : u64 : 40;
}
}

namespace osm_ext {
const u64 INVALID_IDX = 1099511627775;
}

namespace osm_ext {
archive Taginfo
{
    keys : vector< .osm_ext.KeyEntry >;
    values : vector< .osm_ext.ValueEntry >;
    node_post : vector< .osm_ext.Ref >;
    way_post : vector< .osm_ext.Ref >;
    rel_post : vector< .osm_ext.Ref >;
}
}

namespace osm_ext {
archive Ext
{
    @optional
    taginfo : archive .osm_ext.Taginfo;
}
}

"#;
pub const BACKREFS: &str = r#"namespace osm_ext {
struct Range
{
    @range( post )
    first_idx : u64 : 40;
}
}

namespace osm_ext {
struct Ref
{
    value : u64 : 40;
}
}

namespace osm_ext {
const u64 INVALID_IDX = 1099511627775;
}

namespace osm_ext {
archive Backrefs
{
    node_ways_range : vector< .osm_ext.Range >;
    ways_of_node : vector< .osm_ext.Ref >;
    node_rels_range : vector< .osm_ext.Range >;
    rels_of_node : vector< .osm_ext.Ref >;
    way_rels_range : vector< .osm_ext.Range >;
    rels_of_way : vector< .osm_ext.Ref >;
    rel_rels_range : vector< .osm_ext.Range >;
    rels_of_rel : vector< .osm_ext.Ref >;
}
}

namespace osm_ext {
archive Ext
{
    @optional
    backrefs : archive .osm_ext.Backrefs;
}
}

"#;
}
}
}
}
